### ISSUE TITLE
Backward selection mode doesn't select first character

### ISSUE THREAD

**Issue by icher** [lucax88x/CodeAceJumper#110]
Hi, thanks for #108 -- works great, but here's another similar problem:

![Peek 2019-11-13 10-30](https://user-images.githubusercontent.com/8604717/68733468-f8134300-0600-11ea-94fc-6a6d3ee7aef7.gif)

When you're using selection mode backward, first character (place where you're jumped, " in my gif) doesn't selected.

**Comment by lucax88x** [comment]
I'll try to fix today / tomorrow.

**Comment by pe224** [comment]
This is caused by the "fix" of d203104, resp. issue #108.

However, I would argue that it was correct behavior before this commit.
When you simply jump to a character, the cursor is always placed *before* that character.
I personally would expect the selection to end at the final cursor position, i.e.

* jumping forward, the selection ends *before* that character
* jumping backward, again the selection ends *before* that character - meaning that in this case the character is included

There is a point to be made that like this it would never be possible to select until the end of a line (since you cannot jump to linebreaks AFAIK).

If you plan to keep d203104 I would hope for a setting to turn this on or off.

EDIT: thinking about it, it might also make sense to include the selected character - accepting that selection mode just works differently than jumping mode. I don't have a strong opinion on that anymore 😉
